### ISSUE TITLE
Css is not loading

### ISSUE THREAD

**Issue by mastermoin** [nikospara/angular-require-lazy#4]
running success but css problem and all contain are overlapped

**Comment by nikospara** [comment]
That is strange... it is working fine here with a clean installation.

Could you please elaborate/provide more details on the problem? And a copy/screenshot of the browser's console would help too!

Could you also include information about your environment (OS, node version etc). My environment is:

- Linux (hopefully does not matter)
- Node 0.12.0
- Local installation of Grunt
- Firefox 38.0
