### ISSUE TITLE
Angular Require Lazy does not have a License

### ISSUE THREAD

**Issue by mportuga** [nikospara/angular-require-lazy#7]
Hi Nikos! 
We would like to use this, but we are not allowed to use unlicensed code.
Would you be able to add an MIT License to your project?

**Comment by nikospara** [comment]
Hi mportuga,

Sorry for missing this message for all these days. And yes, I had totally missed the license file. I will be adding the MIT license within the day.

Thanks for your interest!

**Comment by mportuga** [comment]
Thank you very much for adding this license, I really appreciate it!
